try:
	a=[1,2,3,4]
	print(a[4])
except Exception as e:
	print (e)		